# Generated by Django 5.0.1 on 2025-10-07 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID Mercado Pago')),
                ('mercadopago_status', models.CharField(blank=True, max_length=50, verbose_name='Status Mercado Pago')),
                ('mercadopago_response', models.JSONField(blank=True, null=True, verbose_name='Resposta Mercado Pago')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Código de Referência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('plan_type', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=20, verbose_name='Tipo de Plano')),
                ('benefits', models.JSONField(default=list, help_text='Lista de benefícios', verbose_name='Benefícios')),
                ('classes_per_week', models.IntegerField(blank=True, null=True, verbose_name='Aulas por Semana')),
                ('has_video_access', models.BooleanField(default=True, verbose_name='Acesso a Vídeos?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('mercadopago_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='ID Assinatura MP')),
                ('auto_renewal', models.BooleanField(default=True, verbose_name='Renovação Automática?')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
